{% set version = "0.5.1" %}

package:
  name: webencodings
  version: {{ version }}

source:
  fn: webencodings-{{ version }}.tar.gz
  url: https://github.com/gsnedders/python-webencodings/archive/v{{ version }}.tar.gz
  sha256: 082367f568a7812aa5f6922ffe3d9d027cd83829dc32bcaac4c874eeed618000

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - webencodings

about:
  home: https://github.com/gsnedders/python-webencodings
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://pythonhosted.org/webencodings
  dev_url: https://github.com/gsnedders/python-webencodings
  summary: Character encoding aliases for legacy web content

extra:
  recipe-maintainers:
    - jschueller
