{% set version = "0.8.1" %}

package:
  name: terminado
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/terminado/terminado-{{ version }}.tar.gz
  sha256: 55abf9ade563b8f9be1f34e4233c7b7bde726059947a593322e8a553cc4c067a

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
  run:
    - python
    - ptyprocess  # [not win]
    - pywinpty  # [win]
    - tornado >=4

test:
  imports:
    - terminado

  requires:
    - nose

  commands:
    # Failing test on osx: https://github.com/conda-forge/staged-recipes/pull/313#issuecomment-208426267
    - nosetests terminado  # [not osx]

about:
  home: http://github.com/mitsuhiko/markupsafe
  license: BSD 3-clause
  summary: Terminals served by tornado websockets

extra:
  recipe-maintainers:
    - blink1073
    - pelson
    - takluyver 
