{% set version = "0.6.2" %}

package:
  name: h5netcdf
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/h5netcdf/h5netcdf-{{ version }}.tar.gz
  sha256: 2d80a8f32854e9dab1ce307d8c8bae722a9133818c951a1a2f635758776c974a

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - h5py
  run:
    - python
    - h5py

test:
  imports:
    - h5netcdf

about:
  home: https://github.com/shoyer/h5netcdf
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'netCDF4 via h5py.'

extra:
  recipe-maintainers:
    - jhamman
    - jjhelmus
    - ocefpaf
    - shoyer
