{% set version = "3.5.0" %}

package:
  name: configparser
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/configparser/configparser-{{ version }}.tar.gz
  sha256: 5308b47021bc2340965c371f0f058cc6971a04502638d4244225c49d80db273a

build:
  number: 1001
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - backports
    - backports.configparser
    - configparser

about:
  home: http://docs.python.org/3/library/configparser.html
  license: MIT
  summary: This library brings the updated configparser from Python 3.5 to Python 2.6-3.5

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - bgruening
