{% set version = "0.1.5" %}
 
package:
  name: s3fs
  version: "{{ version }}"

source:
  fn: s3fs-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/s3fs/s3fs-{{ version }}.tar.gz
  sha256: 4fbab74d72ceeb1a6f249165bde7b1d1c4dd758390339f52c84f0832bc5117a7

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  build:
    - python
    - setuptools
    - boto3
    - pip

  run:
    - python
    - boto3


test:
  imports:
    - s3fs

about:
  home: http://s3fs.readthedocs.io/en/latest/
  license: BSD 3-Clause
  summary: 'Convenient Filesystem interface over S3'

extra:
  recipe-maintainers:
    - martindurant
    - mrocklin
    - koverholt
