{% set name = "webp" %}
{% set version = "1.0.0" %}
{% set sha256 = "84259c4388f18637af3c5a6361536d754a5394492f91be1abc2e981d4983225b" %}

package:
  name: lib{{ name|lower }}
  version: {{ version }}

source:
  fn:  lib{{ name }}-{{ version }}.tar.gz
  url: http://storage.googleapis.com/downloads.webmproject.org/releases/{{name}}/lib{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - jpeg  # [unix]
    - libpng  # [unix]
    - libtiff  # [unix]
    - giflib  # [unix]
  run:
    - jpeg  # [unix]
    - libpng  # [unix]
    - libtiff  # [unix]
    - giflib  # [unix]

test:
  commands:
    - test -f $PREFIX/lib/libwebp.a  # [unix]
    - test -f $PREFIX/lib/libwebp.dylib  # [osx]
    - test -f $PREFIX/lib/libwebp.so  # [linux]
    - test -f $PREFIX/bin/cwebp  # [unix]
    - test -f $PREFIX/bin/dwebp  # [unix]
    - test -f $PREFIX/include/webp/decode.h  # [unix]
    - test -f $PREFIX/include/webp/encode.h  # [unix]
    - test -f $PREFIX/include/webp/types.h  # [unix]
    - if not exist %LIBRARY_LIB%\\libwebp.lib exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\libwebpdecoder.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\cwebp.exe exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\dwebp.exe exit 1  # [win]
    - if not exist %LIBRARY_INC%\\webp\\decode.h exit 1  # [win]
    - if not exist %LIBRARY_INC%\\webp\\encode.h exit 1  # [win]
    - if not exist %LIBRARY_INC%\\webp\\types.h exit 1  # [win]

about:
  home: https://developers.google.com/speed/webp/
  license: Google
  license_file: COPYING
  summary: "WebP image library"
  description: |
    WebP is a method of lossy and lossless compression that can be used on a large variety of photographic,
    translucent and graphical images found on the web. The degree of lossy compression is adjustable so a
    user can choose the trade-off between file size and image quality.
  doc_url: https://developers.google.com/speed/webp/docs/using
  dev_url: https://chromium.googlesource.com/webm/libwebp

extra:
  recipe-maintainers:
    - dschreij
