{% set version = "2.4.1" %}

package:
  name: imageio
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/imageio/imageio-{{ version }}.tar.gz
  sha256: 16b8077bc8a5fa7a58b3e744f7ecbb156d8c088132df31e0f4f546c98de3514a

build:
  number: 1000
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"
  entry_points:
    - imageio_download_bin = imageio.__main__:download_bin_main
    - imageio_remove_bin = imageio.__main__:remove_bin_main

requirements:
  host:
    - pip
    - python
  run:
    - python
    - numpy
    - pillow
    - enum34  # [py<34]
    - futures  # [py<32]

test:
  imports:
    - imageio
  commands:
    - imageio_download_bin -h
    - imageio_remove_bin -h

about:
  home: http://imageio.github.io
  doc_url: http://imageio.readthedocs.io
  dev_url: https://github.com/imageio/imageio
  summary: A Python library for reading and writing image data
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - almarklein
    - blink1073
    - jni
