{% set version = "1.0.0" %}

package:
  name: pywavelets
  version: {{ version }}

source:
  url: https://github.com/PyWavelets/pywt/archive/v{{ version }}.tar.gz
  sha256: 1696cbbbb74d670dda6bb75c0628fd1f82d98750661fcd9bd375082559252de8

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - nose
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME   # [osx]

about:
  home: https://github.com/PyWavelets/pywt
  license: MIT
  license_file: LICENSE
  summary: 'Discrete Wavelet Transforms in Python.'

extra:
  recipe-maintainers:
    - grlee77
    - jakirkham
    - ocefpaf
