{% set version = "0.9.0" %}

package:
  name: statsmodels
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/statsmodels/statsmodels-{{ version }}.tar.gz
  sha256: 6461f93a842c649922c2c9a9bc9d9c4834110b89de8c4af196a791ab8f42ba3b

build:
  number: 1000
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy 1.14.*  # [win]
    - numpy  # [not win]
    - scipy >=0.14
    - pandas >=0.14
    - patsy >=0.4.0
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=0.14
    - pandas >=0.14
    - patsy >=0.4.0

test:
  imports:
    - statsmodels

about:
  home: https://www.statsmodels.org
  license: BSD 3-Clause
  summary: 'Statistical computations and models for use with SciPy'
  dev_url: https://github.com/statsmodels/statsmodels
  doc_url: https://www.statsmodels.org/stable/

extra:
  recipe-maintainers:
    - tomaugspurger
    - croth1
    - ocefpaf
