{% set version = "1.24.1" %}

package:
  name: libuv
  version: {{ version }}

source:
  url: https://github.com/libuv/libuv/archive/v{{ version }}.tar.gz
  sha256: 0d026c8f68c4d7b7c59de8f485f262ac71c24e0f3a80d740a25d20edd2f2774e

build:
  number: 1000
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - automake             # [unix]
    - autoconf             # [unix]
    - libtool              # [unix]
    - make                 # [unix]

test:
  commands:
    - test -f "$PREFIX/include/uv.h"
    - test -f "$PREFIX/lib/libuv.a"  # [unix]
    - test -f "$PREFIX/lib/libuv.so.1"  # [linux]
    - test -f "$PREFIX/lib/libuv.1.dylib"  # [osx]
    - test -f "$PREFIX/lib/libuv${SHLIB_EXT}"  # [not win]

about:
  home: http://libuv.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Cross-platform asynchronous I/O'
  description: |
    libuv is a multi-platform support library with a focus on asynchronous I/O.
    It was primarily developed for use by Node.js, but it's also used by Luvit,
    Julia, pyuv, and others.
  doc_url: http://docs.libuv.org/
  dev_url: https://github.com/libuv/libuv

extra:
  recipe-maintainers:
    - frol
    - mariusvniekerk
