{% set version = "3.5.3" %}

package:
  name: subprocess32
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/subprocess32/subprocess32-{{ version }}.tar.gz
  sha256: 6bc82992316eef3ccff319b5033809801c0c3372709c5f6985299c88ac7225c3

build:
  number: 0
  skip: True  # [not py2k]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - subprocess32

about:
  home: https://github.com/google/python-subprocess32
  license: PSF 2
  summary: 'A backport of the subprocess module from Python 3.2/3.3 for use on 2.x.'

extra:
  recipe-maintainers:
    - tacaswell
    - mdboom
