{% set version = "1.0.3.4" %}

package:
  name: cftime
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cftime/cftime-{{ version }}.tar.gz
  sha256: dd74d0d470baf1c50e31335215793a5e78436903e34b4f151fa9ccbf3a6cc20c

build:
  number: 1000
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  source_files:
    - test
  requires:
    - pytest
  imports:
    - cftime
  commands:
    - pytest -vv test

about:
  home: https://github.com/Unidata/cftime
  license: MIT
  license_file: COPYING
  summary: 'Time-handling functionality from netcdf4-python'

  description: |
    Time-handling functionality from netcdf4-python
  doc_url: https://github.com/Unidata/cftime
  dev_url: https://github.com/Unidata/cftime

extra:
  recipe-maintainers:
    - jhamman
    - ocefpaf
