{% set version = "1.1.0" %}

package:
  name: markupsafe
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/M/MarkupSafe/MarkupSafe-{{ version }}.tar.gz
  sha256: 4e97332c9ce444b0c2c38dd22ddc61c743eb208d916e4265a2a3b575bdccb1d3

build:
  number: 1000
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - markupsafe

about:
  home: https://www.palletsprojects.com/p/markupsafe
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: A Python module that implements the jinja2.Markup string
  dev_url: https://github.com/pallets/markupsafe

extra:
  recipe-maintainers:
    - pelson
    - scopatz
    - ocefpaf
