{% set version = "3.3.8" %}

package:
  name: fftw
  version: {{ version }}

source:
  fn: fftw-{{ version }}.tar.gz
  url: http://www.fftw.org/fftw-{{ version }}.tar.gz
  sha256: 6113262f6e92c5bd474f2875fa1b01054c4ad5040f6b0da7c03c98821d9ae303

build:
  number: 1000

requirements:
  build:
    - perl   # [not win]
    - cmake  # [win]
    - {{ compiler('c') }}
  host:

test:
  commands:
    - exit $(test -f ${PREFIX}/lib/libfftw3f.a)          # [not win]
    - exit $(test -f ${PREFIX}/lib/libfftw3.a)           # [not win]
    - exit $(test -f ${PREFIX}/lib/libfftw3l.a)          # [not win]
    - exit $(test -f ${PREFIX}/lib/libfftw3f_threads.a)  # [not win]
    - exit $(test -f ${PREFIX}/lib/libfftw3_threads.a)   # [not win]
    - exit $(test -f ${PREFIX}/lib/libfftw3l_threads.a)  # [not win]

    # Verify headers are installed
    - test -f ${PREFIX}/include/fftw3.h                  # [not win]
    - if not exist %LIBRARY_INC%\\fftw3.h exit 1         # [win]

    # Verify shared libraries are installed
    {% set fftw_libs = [
            "libfftw3",
            "libfftw3_threads",
            "libfftw3f",
            "libfftw3f_threads",
            "libfftw3l",
            "libfftw3l_threads",
    ] %}

    {% for lib in fftw_libs %}
    - python -c "import ctypes; ctypes.cdll[r'${PREFIX}/lib/{{ lib }}${SHLIB_EXT}']"  # [unix]
    {% endfor %}

    {% set fftw_libs = ["fftw3f", "fftw3"] %}

    {% for base in fftw_libs %}
    - if not exist %LIBRARY_LIB%\\{{ base }}.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\{{ base }}.dll exit 1  # [win]
    {% endfor %}

about:
  home: http://fftw.org
  license: GPL 2
  license_file: COPYING
  summary: "The fastest Fourier transform in the west."

extra:
  recipe-maintainers:
    - alexbw
    - jakirkham
    - jjhelmus
    - grlee77
    - jschueller
