{% set name = "fastcache" %}
{% set version = "1.0.2" %}
{% set sha256 = "867005774917f999854ffd303fbe3793c30c2dc9279b78ec315dd4e57e4284e6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - fastcache
    - fastcache._lrucache

  commands:
    - python -c "import fastcache; fastcache.test()"

  requires:
    - pytest

about:
  home: https://github.com/pbrady/fastcache
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'C implementation of Python 3 lru_cache'
  dev_url: https://github.com/pbrady/fastcache

extra:
  recipe-maintainers:
    - synapticarbors
