{% set version = "0.9.0" %}

package:
  name: smmap
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/smmap/smmap-{{ version }}.tar.gz
  sha256: 0e2b62b497bd5f0afebc002eda4d90df9d209c30ef257e8673c90a6b5c119d62

build:
  noarch: python
  number: 2
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - smmap

about:
  home: https://github.com/gitpython-developers/smmap
  license: BSD 3-Clause
  summary: 'A pure git implementation of a sliding window memory map manager.'

extra:
    recipe-maintainers:
        - pelson
        - ocefpaf
