{% set version = "0.19.2" %}
{% set name = "scikit-learn" %}
{% set variant = "openblas" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b276739a5f863ccacb61999a3067d0895ee291c95502929b2ae56ea1f882e888

build:
  number: 201
  # We lack scipy on Windows, and therefore can't build numpy there either currently.
  skip: true  # [win]
  features:
    - blas_{{ variant }}
  script: python -m pip install --no-deps --ignore-installed .  --verbose

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - cython
    - setuptools
    - blas 1.1 {{ variant }}
    - openblas
    - numpy
    - scipy
    - nose
  run:
    - python
    - blas 1.1 {{ variant }}
    - openblas
    - {{ pin_compatible('numpy') }}
    - scipy

test:
  requires:
    - nose
  imports:
    - sklearn
  commands:
    - nosetests sklearn --exe
    - conda inspect linkages -p $PREFIX scikit-learn  # [not win]
    - conda inspect objects -p $PREFIX scikit-learn  # [osx]

about:
  home: http://scikit-learn.org/
  license: BSD 3-Clause
  license_file: COPYING
  summary: A set of python modules for machine learning and data mining

extra:
  recipe-maintainers:
    - amueller
    - astaric
    - jakirkham
    - ogrisel
    - ocefpaf
    - lesteve
