{% set version = "2.7.15" %}
{% set sha256 = "18617d1f15a380a919d517630a9cd85ce17ea602f9bbdc58ddc672df4b0239db" %}

package:
  name: python
  version: {{ version }}

source:
  fn: Python-{{ version }}.tgz
  url: https://www.python.org/ftp/python/{{ version }}/Python-{{ version }}.tgz
  sha256: {{ sha256 }}

build:
  number: 1
  no_link:
    - bin/python2.7
  script_env:
    - python_branding
  skip_compile_pyc:
    - lib/python2.7/test/*bad*.py
  ignore_prefix_files:
    - lib/libpython2.7.so.1.0
    - lib/python2.7/lib-dynload/*.so
  # We delete the shared libraries
  ignore_run_export:
    - bzip2

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - pkg-config
  host:
    - bzip2
    - sqlite
    - zlib
    - openssl
    - readline
    - tk
    - ncurses

test:
  commands:
    - python -V
    - pydoc -h
    - python-config --help
    - idle -h

about:
  home: http://www.python.org/
  license: PSF
  summary: General purpose programming language
