{% set version = "0.6.1" %}

package:
  name: mccabe
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/mccabe/mccabe-{{ version }}.tar.gz
  sha256: dd8d182285a0fe56bace7f45b5e7d1a6ebcbf524e8f3bd87eb0f125271b8831f

build:
  number: 1
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - pytest-runner
  run:
    - python

test:
  imports:
    - mccabe

about:
  home: https://github.com/PyCQA/mccabe
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'McCabe complexity checker for Python'
  dev_url: https://github.com/PyCQA/mccabe

extra:
  recipe-maintainers:
    - jakirkham
    - sigmavirus24
    - ocefpaf
    - dopplershift
