{% set name = "pytest-remotedata" %}
{% set version = "0.3.0" %}
{% set git_url = "https://github.com/astropy/pytest-remotedata" %}
{% set sha256 = "cb0a6e22ba07ff870edeb17d5d38c495e8f37e2db741cd15e723fb8e609909eb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - pytest >=3.1
    - six
  run:
    - python
    - pytest >=3.1
    - six

test:
  imports:
    - pytest_remotedata

about:
  home: {{ git_url }}
  license: BSD
  summary: 'Pytest plugin for controlling remote data access'
  description: |
    This package provides a plugin for the pytest framework that allows
    developers to control unit tests that require access to data from the
    internet.
  doc_url: {{ git_url }}
  dev_url: {{ git_url }}

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
    - drdavella
    - mwcraig
