{% set version = "2.3.3" %}

package:
  name: pathlib2
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pathlib2/pathlib2-{{ version }}.tar.gz
  sha256: 25199318e8cc3c25dcb45cbe084cc061051336d5a9ea2a12448d3d8cb748f742

build:
  number: 1000
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six
    - scandir  # [py27]

test:
  imports:
    - pathlib2

about:
  home: https://github.com/mcmtroffaes/pathlib2
  license: MIT
  license_file: LICENSE.rst
  summary: "Fork of pathlib aiming to support the full stdlib Python API"

extra:
  recipe-maintainers:
    - pelson
    - takluyver
