{% set name = "functools32" %}
{% set version = "3.2.3" %}
{% set subversion = "2" %}
{% set number = 2 %}
{% set sha256 = "f6253dfbe0538ad2e387bd8fdfd9293c925d63553f5813c4e587745416501e6d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}.{{ subversion }}

source:
  fn: {{ name }}-{{ version }}-{{ subversion }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}-{{ subversion }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [not py27]
  number: {{ number }}
  script: python setup.py install

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - functools32

about:
  home: https://github.com/MiCHiLU/python-functools32
  license: PSF 2
  license_file: LICENSE
  summary: 'Backport of the functools module from Python 3.2.3 for use on 2.7 and PyPy.'

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
