# Jinja variables help maintain the recipe as you'll update the version only here.
{% set version = "4.2.1" %}
{% set sha256 = "d6e262bf3601b42d2b1e4ef8310029e1dcf20083c5446b4b7aa67081fdffc589" %}

package:
  name: make
  version: {{ version }}

source:
  fn: make-{{ version }}.tar.bz2
  url: ftp://ftp.halifax.rwth-aachen.de/gnu/make/make-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 1

requirements:
  build:
    - {{ compiler("c") }}        # [unix]
    - {{ compiler("m2w64_c") }}  # [win]

test:
  commands:
    - $PREFIX/bin/make --help  # [unix]
    - '"%LIBRARY_BIN%\gnumake.exe" --help'  # [win]

about:
  home: https://www.gnu.org/software/make/
  license: GPLv3
  summary: >-
    GNU Make is a tool which controls the generation of executables and other
    non-source files of a program from the program's source files.

extra:
  recipe-maintainers:
    - asmeurer
    - scopatz
