{% set version = "2.1.17" %}

package:
  name: conda-build
  version: {{ version }}

source:
  fn: conda-build-{{ version }}.tar.gz
  url: https://github.com/conda/conda-build/archive/{{ version }}.tar.gz
  sha256: 1ec14c7aa8523042a5717e69fd0fbf5bf444ec4fe4eb0d42a32c3b0a62a7b543

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - conda-build = conda_build.cli.main_build:main
    - conda-convert = conda_build.cli.main_convert:main
    - conda-develop = conda_build.cli.main_develop:main
    - conda-index = conda_build.cli.main_index:main
    - conda-inspect = conda_build.cli.main_inspect:main
    - conda-metapackage = conda_build.cli.main_metapackage:main
    - conda-render = conda_build.cli.main_render:main
    - conda-sign = conda_build.cli.main_sign:main
    - conda-skeleton = conda_build.cli.main_skeleton:main

requirements:
  build:
    - python
    - setuptools

  run:
    - beautifulsoup4
    - chardet
    - conda >=4.1,<4.4
    - contextlib2   # [py27]
    - conda-verify
    - enum34        # [py27]
    - filelock
    - futures       # [py27]
    - jinja2
    - patchelf      # [linux]
    - pkginfo
    - pycrypto
    - python
    - pyyaml
    - six

test:
  # If you run the test suite (~10 min), these are required
  # requires:
  #   - pytest
  #   - pytest-timeout
  #   - pytest-catchlog
  imports:
    - conda_build

  commands:
    - which conda-build
    - conda-build -h
    - which conda-convert
    - conda-convert -h
    - which conda-develop
    - conda-develop -h
    - which conda-index
    - conda-index -h
    - which conda-inspect
    - conda-inspect linkages -h \| grep "--name ENVIRONMENT"
    - conda-inspect -h
    - which conda-metapackage
    - conda-metapackage -h
    - which conda-render
    - conda-render -h
    - which conda-sign
    - conda-sign -h
    - which conda-skeleton
    - conda-skeleton -h

about:
  home: https://github.com/conda/conda-build
  summary: tools for building conda packages
  license: BSD 3-Clause
