{% set version = "0.7.4" %}

package:
  name: pickleshare
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pickleshare/pickleshare-{{ version }}.tar.gz
  sha256: 84a9257227dfdd6fe1b4be1319096c20eb85ff1e82c7932f36efccfe1b09737b

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - pathlib2  # [py<34]

test:
  imports:
    - pickleshare

about:
  home: https://github.com/vivainio/pickleshare
  license: MIT
  summary: "Tiny 'shelve'-like database with concurrency support"

extra:
  recipe-maintainers:
    - pelson
    - takluyver
    - ocefpaf
