{% set name = "sphinxcontrib-websupport" %}
{% set version = "1.1.0" %}
{% set sha256 = "9de47f375baf1ea07cdb3436ff39d7a9c76042c10a769c52353ec46e4e8fc3b9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - sphinxcontrib

about:
  home: https://pypi.python.org/pypi/sphinxcontrib-websupport
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Sphinx API for Web Apps'
  description: |
    sphinxcontrib-websupport provides a Python API to easily integrate
    Sphinx documentation into your Web application
  doc_url: http://www.sphinx-doc.org/en/stable/
  dev_url: https://github.com/sphinx-doc/sphinxcontrib-websupport

extra:
  recipe-maintainers:
    - chohner
