{% set version = "2018.8.13" %}

package:
  name: certifi
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/certifi/certifi-{{ version }}.tar.gz
  sha256: 4c1d68a1408dd090d2f3a869aa94c3947cc1d967821d1ed303208c9f41f0f2f4

build:
  number: 0
  preserve_egg_dir: True
  script: python setup.py install

requirements:
  build:
    - python
  run:
    - python

test:
  imports:
    - certifi

about:
  home: http://certifi.io/
  license: ISC
  license_file: LICENSE
  summary: Python package for providing Mozilla's CA Bundle.

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - sigmavirus24
    - ocefpaf
