{% set name = "bleach" %}
{% set version = "2.1.3" %}
{% set sha256 = "eb7386f632349d10d9ce9d4a838b134d4731571851149f9cc2c05a9a837a9a44" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: pip install --no-deps .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - html5lib >=0.99999999pre,!=1.0b1,!=1.0b2,!=1.0b3,!=1.0b4,!=1.0b5,!=1.0b6,!=1.0b7,!=1.0b8
    - setuptools
    - six

test:
  imports:
    - bleach

about:
  home: https://github.com/mozilla/bleach
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Bleach is a whitelist-based HTML sanitizing library that escapes or strips markup and attributes.

  dev_url: https://github.com/mozilla/bleach
  doc_url: https://bleach.readthedocs.io/

extra:
  recipe-maintainers:
    - minrk
