{% set version = "1.0.0" %}

package:
  name: heapdict
  version: {{ version }}

source:
  url: https://github.com/DanielStutzbach/heapdict/archive/v{{ version }}.tar.gz
  sha256: 4c8e581f1651ca78da35820fc80b0d50fc060032517f2c7efd9169e204db3793

build:
  number: 1000
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - heapdict

about:
  home: http://stutzbachenterprises.com/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'A Heap MutableMapping'

extra:
  recipe-maintainers:
    - mrocklin
    - ocefpaf
