{% set name = "astroid" %}
{% set version = "1.6.5" %}
{% set sha256 = "fc9b582dba0366e63540982c3944a9230cbc6f303641c51483fa547dcc22393a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - setuptools
    - enum34  # [py2k]
    - singledispatch  # [py2k]
    - backports.functools_lru_cache  # [py2k]
    - six
    - lazy-object-proxy
    - wrapt

test:
  imports:
    - astroid
    - astroid.tests
    # import modutils to expose the setuptools runtime requirement
    - astroid.modutils

about:
  home: https://github.com/PyCQA/astroid
  license: LGPL 2.1
  license_file: COPYING.LESSER
  summary: 'A abstract syntax tree for Python with inference support.'

extra:
  recipe-maintainers:
    - ericdill
    - jakirkham
