{% set version = "1.25.0" %}

package:
  name: pytest-xdist
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pytest-xdist/pytest-xdist-{{ version }}.tar.gz
  sha256: 96f893094c89fddeaff3f4783f4807f7aeb138be1a0d87a8805057b6af1201b5

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} setup.py install --single-version-externally-managed --record record.txt"

requirements:
  host:
    - python
    - pip
    - setuptools_scm
  run:
    - python
    - execnet >=1.1
    - pytest >=3.0.0
    - pytest-forked
    - six

test:
  imports:
    - xdist
  files:
    - dummy_test.py
  commands:
    - pytest -n2 dummy_test.py

about:
  home: https://github.com/pytest-dev/pytest-xdist
  license: MIT
  license_file: LICENSE
  summary: py.test xdist plugin for distributed testing and loop-on-failing modes
  dev_url: https://github.com/pytest-dev/pytest-xdist

extra:
  recipe-maintainers:
    - goanpeca
    - nicoddemus
