{% set version = "0.4.4" %}

package:
  name: pyasn1
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pyasn1/pyasn1-{{ version }}.tar.gz
  sha256: f58f2a3d12fd754aa123e9fa74fb7345333000a035f3921dbdaa08597aa53137

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pyasn1
    - pyasn1.codec
    - pyasn1.codec.ber
    - pyasn1.codec.cer
    - pyasn1.codec.der
    - pyasn1.compat
    - pyasn1.type

about:
  home: https://github.com/etingof/pyasn1
  license: BSD 2-Clause
  license_file: LICENSE.rst
  license_family: BSD
  summary: 'ASN.1 types and codecs'
  description: |
    Pure-Python implementation of ASN.1 types and DER/BER/CER codecs (X.208)
  doc_url: http://pyasn1.sourceforge.net/
  doc_source_url: https://github.com/etingof/pyasn1/blob/master/doc/source/contents.rst
  dev_url: https://github.com/etingof/pyasn1

extra:
  recipe-maintainers:
    - pmlandwehr
