{% set version = "3.5.6" %}

package:
  name: python
  version: {{ version }}

source:
  fn: Python-{{ version }}.tgz
  url: https://www.python.org/ftp/python/{{ version }}/Python-{{ version }}.tgz
  md5: 99a7e803633a627b264a42ce976d8c19

build:
  number: 0
  no_link:
    - bin/python3.5
  script_env:
    - python_branding
  skip_compile_pyc:
    - lib/python3.5/test/*bad*.py
    - lib/python3.5/lib2to3/tests/data/*.py
  ignore_prefix_files:
    - lib/libpython3.5m.so.1.0
    - lib/python3.5/lib-dynload/*.so
  # We delete the shared libraries.
  ignore_run_exports:
    - bzip2

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - pkg-config
  host:
    - bzip2
    - sqlite
    - xz
    - zlib
    - openssl
    - readline
    - tk
    - ncurses

test:
  commands:
    - python -V
    - python3 -V
    - 2to3 -h
    - pydoc -h
    - python3-config --help

about:
  home: http://www.python.org/
  license: PSF
  summary: General purpose programming language
