{% set version = "5.2.4" %}

package:
  name: jupyter_client
  version: {{ version }}

source:
  fn: jupyter_client-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/j/jupyter_client/jupyter_client-{{ version }}.tar.gz
  sha256: b5f9cb06105c1d2d30719db5ffb3ea67da60919fb68deaefa583deccd8813551

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - jupyter-kernelspec = jupyter_client.kernelspecapp:KernelSpecApp.launch_instance
    - jupyter-run = jupyter_client.runapp:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - traitlets
    - jupyter_core
    - python-dateutil >=2.1
    - pyzmq >=13
    - tornado

test:
  commands:
    - jupyter kernelspec list
    - jupyter run -h
  imports:
    - jupyter_client

about:
  home: http://jupyter.org
  license: BSD 3-clause
  license_file: COPYING.md
  summary: jupyter_client contains the reference implementation of the Jupyter protocol.

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - pelson
    - ocefpaf
    - carreau
