{% set version = "0.9.0" %}

package:
  name: toolz
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/toolz/toolz-{{ version }}.tar.gz
  sha256: 929f0a7ea7f61c178bd951bdae93920515d3fbdbafc8e6caf82d752b9b3b31c9
  patches:
    # https://github.com/pytoolz/toolz/pull/405
    - backport_405.patch

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - toolz
    - toolz.curried
    - toolz.functoolz
    - toolz.sandbox

about:
  home: http://toolz.readthedocs.org/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: A functional standard library for Python

extra:
  recipe-maintainers:
    - mrocklin
    - eriknw
    - jcrist
    - jakirkham
    - ocefpaf
