{% set version = "1.16.1" %}
{% set build = 1001 %}
{% set sha256 = "608a97523f97db32f1f5d5615c98ca69326ced2054c9f82e65bade7fc4c9dea8" %}

package:
  name: automake
  version: {{ version }}

source:
  url: http://ftp.gnu.org/gnu/automake/automake-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  skip: true  # [win]

requirements:
  host:
    - m4
    - autoconf
    - perl
  run:
    - m4
    - autoconf
    - perl

test:
  commands:
    - automake --help

about:
  home: http://www.gnu.org/software/automake/
  license: GPL-2.0
  license_family: GPL
  license_file: COPYING
  summary: >
             Tool for automatically generating Makefile.in files compliant with
             the GNU Coding Standards.

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
