{% set version = "1.0.2o" %}

package:
  name: openssl
  version: {{ version }}

source:
  url: http://www.openssl.org/source/openssl-{{ version }}.tar.gz
  sha256: ec3f5c9714ba0fd45cb4e087301eb1336c317e0d20b575a125050470e8089e4d

build:
  number: 1
  no_link: lib/libcrypto.so.1.0.0        # [linux]
  no_link: lib/libcrypto.1.0.0.dylib     # [osx]
  detect_binary_files_with_prefix: True  # [unix]
  has_prefix_files:                      # [unix]
    - bin/c_rehash                       # [unix]
    - include/openssl/opensslconf.h      # [unix]
    - lib/pkgconfig/libcrypto.pc         # [unix]
    - lib/pkgconfig/libssl.pc            # [unix]
    - lib/pkgconfig/openssl.pc           # [unix]

requirements:
  build:
    - {{ compiler('c') }}
    - yasm               # [win32]
    - perl
    - make               # [unix]
  run:
    - ca-certificates

test:
  imports:
    - ssl
  commands:
    - copy NUL checksum.txt        # [win]
    - touch checksum.txt           # [unix]
    - openssl sha256 checksum.txt

about:
  home: http://www.openssl.org/
  license_file: LICENSE
  license: OpenSSL
  license_family: Apache
  summary: OpenSSL is an open-source implementation of the SSL and TLS protocols
  dev_url: https://github.com/openssl/openssl
  doc_url: https://www.openssl.org/docs/man1.0.2/

extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - msarahan
    - ocefpaf
    - pelson
