{% set version = "1.2.1" %}

package:
  name: bottleneck
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/B/Bottleneck/Bottleneck-{{ version }}.tar.gz
  sha256: 6efcde5f830aed64feafca0359b51db0e184c72af8ba6675b4a99f263922eb36

build:
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - nose
  imports:
    - bottleneck
    - bottleneck.slow
    - bottleneck.tests
    - bottleneck.reduce
    - bottleneck.nonreduce
    - bottleneck.nonreduce_axis
    - bottleneck.move
  commands:
    - python -c "import bottleneck; bottleneck.test()"
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://berkeleyanalytics.com/bottleneck
  license: BSD 2-Clause
  license_family: BSD
  license_file: bottleneck/LICENSE
  summary: Fast NumPy array functions written in Cython.
  description: |
    Bottleneck is a collection of fast NumPy array functions written in
    Cython.
  doc_url: http://berkeleyanalytics.com/bottleneck
  dev_url: https://github.com/kwgoodman/bottleneck

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - wesm
    - ocefpaf
