{% set version = "2.0.4" %}

package:
  name: smmap2
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/smmap2/smmap2-{{ version }}.tar.gz
  sha256: dc216005e529d57007ace27048eb336dcecb7fc413cfb3b2f402bb25972b69c6

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - smmap

about:
  home: https://github.com/gitpython-developers/smmap
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'A pure python implementation of a sliding window memory map manager'

extra:
  recipe-maintainers:
    - ocefpaf
