{% set version = "2.0.5" %}

package:
  name: smmap2
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/smmap2/smmap2-{{ version }}.tar.gz
  sha256: 29a9ffa0497e7f2be94ca0ed1ca1aa3cd4cf25a1f6b4f5f87f74b46ed91d609a

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - smmap

about:
  home: https://github.com/gitpython-developers/smmap
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'A pure python implementation of a sliding window memory map manager'

extra:
  recipe-maintainers:
    - ocefpaf
