{% set version = "4.9.0" %}

package:
  name: ipykernel
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ipykernel/ipykernel-{{ version }}.tar.gz
  sha256: c5a498c70f7765c34f3397cf943b069057f5bef4e0218e4cfbb733e9f38fa5fa

build:
  number: 0
  script:
    - "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
    - python -m ipykernel install --prefix $PREFIX  # [not win]
    - python -m ipykernel install --prefix %PREFIX%  # [win]

requirements:
  build:
    - pip
    - python
    - jupyter_client
    - ipython >=4.0
    - tornado >=4.0
  run:
    - python
    - ipython >=4.0
    - traitlets >=4.1
    - jupyter_client
    - tornado >=4.0

test:
  imports:
    - ipykernel

about:
  home: http://ipython.org
  license: BSD 3-clause
  license_file: COPYING.md
  summary: IPython Kernel for Jupyter

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - minrk
    - ocefpaf
    - blink1073
