{% set name = "testpath" %}
{% set version = "0.3.1" %}
{% set sha256 = "0d5337839c788da5900df70f8e01015aec141aa3fe7936cb0d0a2953f7ac7609" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: pip install --no-deps .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - pathlib2  # [py2k]

test:
  imports:
    - testpath

about:
  home: https://testpath.readthedocs.io
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Testpath is a collection of utilities for Python code working with files and commands.
  description: |
    Testpath contains functions to check things on the filesystem,
    and tools for mocking system commands and recording calls to those.
  doc_url: https://testpath.readthedocs.io
  dev_url: https://github.com/jupyter/testpath

extra:
  recipe-maintainers:
    - minrk
    - takluyver
