{% set version = "6.5" %}

package:
  name: texinfo
  version: {{ version }}

source:
  fn: texinfo-{{ version }}.tar.gz
  url: http://ftp.gnu.org/gnu/texinfo/texinfo-{{ version }}.tar.gz
  sha256: d34272e4042c46186ddcd66bd5d980c0ca14ff734444686ccf8131f6ec8b1427

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - perl
  run:
    - perl

test:
  commands:
    - makeinfo -h
    #- conda inspect linkages -p $PREFIX texinfo  # [not win]
    #- conda inspect objects -p $PREFIX texinfo  # [osx]

about:
  home: http://www.gnu.org/software/texinfo/
  license: GPL-2.0 and GPL-3.0
  summary: 'The GNU Documentation System.'

extra:
  recipe-maintainers:
    - pelson
    - rhattersley
    - ocefpaf
