ctng_sample:
  - armv7-rpi2-linux-gnueabihf
ctng_cpu_arch:
  - armv7l
ctng_gcc:
  - 8.2.0
ctng_vendor:
  - rpi3
ctng_target_platform:
  - linux-armv7l
zip_keys:
  -
    - ctng_target_platform
    - ctng_cpu_arch
